# Generated by Django 4.2.7 on 2025-11-12 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="计划编号"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="计划名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("scheduled", "已安排"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "planned_start",
                    models.DateField(blank=True, null=True, verbose_name="计划开始"),
                ),
                (
                    "planned_end",
                    models.DateField(blank=True, null=True, verbose_name="计划结束"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="计划数量",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "生产计划",
                "verbose_name_plural": "生产计划",
                "db_table": "production_plans",
            },
        ),
    ]
