# Generated by Django 4.2.7 on 2025-11-12 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="商户名称")),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="唯一标识"
                    ),
                ),
                ("logo", models.URLField(blank=True, null=True, verbose_name="Logo")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "商户",
                "verbose_name_plural": "商户",
                "db_table": "merchants",
            },
        ),
        migrations.CreateModel(
            name="MerchantSubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="套餐名称")),
                ("code", models.SlugField(unique=True, verbose_name="套餐编码")),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="月费"
                    ),
                ),
                (
                    "yearly_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="年费"
                    ),
                ),
                ("features", models.JSONField(default=list, verbose_name="功能清单")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
            ],
            options={
                "verbose_name": "商户套餐",
                "verbose_name_plural": "商户套餐",
                "db_table": "merchant_plans",
            },
        ),
        migrations.CreateModel(
            name="MerchantSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "有效"),
                            ("expired", "已过期"),
                            ("cancelled", "已取消"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="users.merchant",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.merchantsubscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "商户订阅",
                "verbose_name_plural": "商户订阅",
                "db_table": "merchant_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="MerchantMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "管理员"), ("staff", "员工")],
                        default="admin",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="users.merchant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "商户成员",
                "verbose_name_plural": "商户成员",
                "db_table": "merchant_memberships",
                "unique_together": {("user", "merchant")},
            },
        ),
    ]
