# Generated by Django 4.2.7 on 2025-11-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_merchant_merchantsubscriptionplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="users.merchant",
            ),
        ),
    ]
