# Generated by Django 4.2.16 on 2025-11-12 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customerprofile_merchant"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "check_in_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="签到时间"
                    ),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="签退时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "出勤"),
                            ("late", "迟到"),
                            ("absent", "缺勤"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "考勤记录",
                "verbose_name_plural": "考勤记录",
                "db_table": "attendance_records",
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="attendance__user_id_3daa40_idx"
                    )
                ],
            },
        ),
    ]
