# Generated by Django 4.2.7 on 2025-11-12 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="设备名称")),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="型号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "空闲"),
                            ("running", "运行中"),
                            ("maintenance", "维护"),
                            ("error", "故障"),
                        ],
                        default="idle",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="位置"),
                ),
                (
                    "last_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="上次维护日期"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
                "db_table": "equipment",
            },
        ),
    ]
