# Generated by Django 4.2.7 on 2025-11-12 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="用量"
                    ),
                ),
                (
                    "waste_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="损耗率"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "物料清单",
                "verbose_name_plural": "物料清单",
                "db_table": "bom",
            },
        ),
        migrations.CreateModel(
            name="ConfigOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="选项名称")),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="价格调整",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="显示顺序"),
                ),
            ],
            options={
                "verbose_name": "配置选项",
                "verbose_name_plural": "配置选项",
                "db_table": "config_options",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="物料名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ink", "墨水"),
                            ("substrate", "基材"),
                            ("coating", "涂层"),
                            ("accessory", "辅料"),
                        ],
                        max_length=50,
                        verbose_name="物料分类",
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="规格型号"
                    ),
                ),
                ("unit", models.CharField(max_length=20, verbose_name="单位")),
                (
                    "stock_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="库存数量",
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="最低库存",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(blank=True, max_length=255, verbose_name="供应商"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "物料",
                "verbose_name_plural": "物料",
                "db_table": "materials",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="产品名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("uv_roll", "UV卷材"),
                            ("banner", "喷绘布"),
                            ("car_sticker", "车贴"),
                            ("lightbox", "灯箱片"),
                            ("kt_board", "KT板"),
                            ("pvc_board", "PVC板"),
                        ],
                        max_length=50,
                        verbose_name="产品分类",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="产品描述")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基础价格"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="平方米", max_length=20, verbose_name="单位"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("images", models.JSONField(default=list, verbose_name="产品图片")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "产品",
                "verbose_name_plural": "产品",
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("size", "尺寸"),
                            ("material", "材料"),
                            ("process", "工艺"),
                            ("color", "颜色"),
                            ("finish", "后处理"),
                        ],
                        max_length=50,
                        verbose_name="配置类型",
                    ),
                ),
                (
                    "config_name",
                    models.CharField(max_length=100, verbose_name="配置名称"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="是否必填"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="显示顺序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品配置",
                "verbose_name_plural": "产品配置",
                "db_table": "product_configs",
                "ordering": ["display_order"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="products_categor_fce6e6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="products_is_acti_cb485f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["category"], name="materials_categor_183e9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["is_active"], name="materials_is_acti_c341ca_idx"
            ),
        ),
        migrations.AddField(
            model_name="configoption",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="products.productconfig",
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boms",
                to="products.material",
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boms",
                to="products.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bom",
            unique_together={("product", "material")},
        ),
    ]
