# Generated by Django 4.2.7 on 2025-11-12 11:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="属性名")),
                ("key", models.CharField(max_length=100, verbose_name="键")),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("select", "选择"),
                            ("number", "数字"),
                            ("text", "文本"),
                            ("size", "尺寸"),
                        ],
                        default="select",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("required", models.BooleanField(default=False, verbose_name="必填")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "目录属性",
                "verbose_name_plural": "目录属性",
                "db_table": "catalog_attributes",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CatalogOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="选项名")),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="加价"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.catalogattribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "目录选项",
                "verbose_name_plural": "目录选项",
                "db_table": "catalog_options",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CatalogCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="标识"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.catalogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "目录分类",
                "verbose_name_plural": "目录分类",
                "db_table": "catalog_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="catalogattribute",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="products.catalogcategory",
            ),
        ),
    ]
