# Generated by Django 4.2.7 on 2025-11-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_merchant_merchantsubscriptionplan_and_more"),
        ("products", "0002_catalogattribute_catalogoption_catalogcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogcategory",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_categories",
                to="users.merchant",
            ),
        ),
    ]
