# Generated by Django 4.2.7 on 2025-11-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_merchant_merchantsubscriptionplan_and_more"),
        ("products", "0003_catalogcategory_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="users.merchant",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["merchant"], name="products_merchan_745db4_idx"),
        ),
    ]
